spring:
  application:
    name: zuul
#禁止配置中心的配置将客户端配置覆盖掉
  cloud:
    config:
      override-none: true 
  rabbitmq:
   host: 193.112.194.209
   port: 5672
   username: admin
   password: admin 
      
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#默认的路由规则(根据eureka注册表)
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50
#zuul 已经包含 actuator依赖
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream           